# Samples and conditions
samples:
  - "sample1"
  - "sample2"
  - "sample3"
  - "sample4"
  - "sample5"
  - "sample6"

treatment_samples:
  - "sample2"
  - "sample3"
  - "sample5"

control_samples:
  - "sample1"
  - "sample4"
  - "sample6"

# Batch information (if applicable)
batch_var: "batch"

# Reference files
# Specify paths to your reference genome and annotation files
genome_fasta: "/path/to/your/genome.fa"
gtf_file: "/path/to/your/annotation.gtf"
te_gtf_file: "/path/to/your/te_annotation.gtf"  # Path to your pre-existing TE GTF file

# Computational resources
threads:
  star_index: 12
  star_align: 8
  samtools: 8
  tetx: 8