# Samples and conditions
samples:
  - "sample1"
  - "sample2"
  - "sample3"
  - "sample4"
  - "sample5"
  - "sample6"

treatment_samples:
  - "sample2"
  - "sample3"
  - "sample5"

control_samples:
  - "sample1"
  - "sample4"
  - "sample6"

# Batch information (if applicable)
batch_var: "batch"

# Reference files
# Available options: "GRCh38", "GRCh37", "GRCm39", "GRCm38", "custom"
genome_build: "GRCm39"

# If using custom genome, specify paths here (ignored if using predefined genome)
custom_genome: "/path/to/custom/genome.fa"
custom_gtf: "/path/to/custom/genes.gtf"

# Directory to store reference files
reference_dir: "resources/references"

# RepeatMasker species 
# Common options: human, mouse, rat, mammal, etc. - see RepeatMasker documentation
species: "mouse"  # for RepeatMasker

# Computational resources
threads:
  star_index: 12
  star_align: 8
  repeatmasker: 8
  samtools: 8
  tetx: 8