name: te_analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - snakemake=7.25.0
  - star=2.7.10b
  - repeatmasker=4.1.5
  - fastqc=0.12.1
  - multiqc=1.14
  - samtools=1.17
  - r-base=4.2
  - r-tidyverse
  - bioconductor-deseq2
  - pip
  - pip:
      - TEtranscripts==2.2.3
  # No pip package available for rmsk2gtf, using custom script instead